spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    org.springframework: ERROR
    com.triplepi: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log